version: '2'
services:
  moodleL:
    image: docker.io/bitnami/moodle:latest
    ports:
      - '81:8080'
      - '4433:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_dataL:/bitnami/moodle'
      - 'moodledata_dataL:/bitnami/moodledata'
    depends_on:
      - mariadb
volumes:
  mariadb_dataL:
    driver: local
  moodle_dataL:
    driver: local
  moodledata_dataL:
    driver: local
